version: '3.7'
name: telogs
services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        image: server
        container_name: telogs_server
        ports:
            - ${SERVER_PORT}:80
        volumes:
            - ../:/var/www/html
        environment:
            SERVER_PORT: ${SERVER_PORT}
    redis:
        image: redis:6
        container_name: telogs_redis
        volumes:
            - ./data/redis:/data/redis
        ports:
            - ${REDIS_PORT}:6379
